### ISSUE TITLE
question: how would you approach eliminating the need for `redis` by leveraging the async ecosystem (event loop)?

### ISSUE THREAD

**Issue by okeyokoro** [cosmicpython/code#15]
hey Harry & Bob,

thanks so much for writing this amazing book (and open-sourcing it!),
I got myself a copy off ebooks.com this weekend 💪🏾

---

 I've been looking at the async ecosystem;

apart from the performance gains, another very attractive feature is the ability to queue tasks to be executed later on in the event loop (basically eliminating a particular usecase for celery/redis)

I'd like to know how you would go about modifying the current implementation to take advantage of async features

**Comment by okeyokoro** [comment]
examples/proof:
https://fastapi.tiangolo.com/tutorial/background-tasks/
https://www.mattlayman.com/blog/2019/starlette-mock-service/

**Comment by hjwp** [comment]
you're putting redis and celery in the same bucket, so I assume that means you're using redis as some sort of task queue (rather than as a generic key/value database, or as a caching system).

either way, i think one way you could use asyncio in our suggested architecture is in the message bus.  since each task on the bus is meant to be independent, you could schedule them asynchronously rather than in a blocking way.  that might give you better performance for web requests.  you'd have to be quite careful about error handling, specifically detecting and surfacing errors and things you want to retry.

have you read the various events chapters? 8-11?

**Comment by okeyokoro** [comment]
> you're putting redis and celery in the same bucket, so I assume that means you're using redis as some sort of task queue

^ correct,

I realize that in the book, redis is used for integrating 3rd party services (sorry if that caused any confusion)

> You could use asyncio in ... the message bus

yes, this is what i had in mind, because as-is when a command gets passed from an entrypoint (flask) to the message bus, the message bus calls the command-handler, which may then emit domain events onto the message bus queue, and those events get passed to event-handlers...all-the-while blocking the initial web request.

I'm suggesting handling the aforementioned domain events more asynchronously (instead of adding them to the message bus queue, we pass them off to: the event loop [or a traditional celery/redis setup, or kafka, <- like suggested in the book ])

> you'd have to be quite careful about error handling, specifically detecting and surfacing errors and things you want to retry

👍, i guess i would still have to fallback to a queue, in the event of an error. thanks for the heads up

> have you read the various events chapters? 8-11?

yup, read the book cover to cover, and i'm now trying to implement the architecture on a medium-sized side project 😄

the first obstacle i faced was folder structure; for a project with multiple bounded contexts, it was a little unclear how things would change.  I finally settled on a structure that looks like:

<details>

```
.
├── __init__.py
├── bootstrap.py
├── config.py
├── bounded_context_2
│   ├── __init__.py
│   ├── adapters
│   │   ├── __init__.py
│   │   ├── abcs.py
│   │   ├── email_server.py
│   │   ├── mappers
│   │   │   ├── __init__.py
│   │   │   ├── document_mapper.py
│   │   │   └── sql_mapper.py
│   │   ├── repositories
│   │   │   ├── __init__.py
│   │   │   ├── abcs.py
│   │   │   ├── inmemory_repo.py
│   │   │   ├── nosql_repo.py
│   │   │   └── sql_repo.py
│   │   ├── task_queue.py
│   │   └── unit_of_work
│   │       ├── __init__.py
│   │       └── abcs.py
│   ├── domain
│   │   ├── __init__.py
│   │   ├── events
│   │   │   ├── __init__.py
│   │   │   └── abcs.py
│   │   ├── messages
│   │   │   ├── __init__.py
│   │   │   ├── commands
│   │   │   │   └── __init__.py
│   │   │   └── queries
│   │   │       └── __init__.py
│   │   └── models
│   │       ├── __init__.py
│   │       ├── abcs.py
│   │       ├── aggregates
│   │       │   ├── __init__.py
│   │       │   └── abcs.py
│   │       ├── entities
│   │       │   └── __init__.py
│   │       ├── services.py
│   │       └── value_objects
│   │           └── __init__.py
│   ├── entrypoints
│   │   ├── __init__.py
│   │   ├── fastapi_routers
│   │   │   ├── __init__.py
│   │   │   └── items
│   │   │       ├── __init__.py
│   │   │       └── schemas.py
│   │   └── flask_blueprints
│   │       ├── __init__.py
│   │       └── rooms
│   │           ├── __init__.py
│   │           └── schemas.py
│   ├── persistence
│   │   ├── __init__.py
│   │   ├── document_collections.py
│   │   └── sql_tables.py
│   ├── tests
│   │   ├── e2e
│   │   │   └── __init__.py
│   │   ├── features
│   │   │   ├── feature.feature
│   │   │   └── step_defs
│   │   │       └── __init__.py
│   │   ├── integration
│   │   │   └── __init__.py
│   │   └── unit
│   │       └── __init__.py
│   └── usecases
│       ├── README.md
│       ├── __init__.py
│       ├── abcs.py
│       ├── command_usecases
│       │   └── __init__.py
│       └── query_usecases
│           └── __init__.py
|
├── bounded_context_2
│   ├── __init__.py
│   ├── adapters
│   │   ├── __init__.py
│   │   ├── abcs.py
│   │   ├── email_server.py
│   │   ├── mappers
│   │   │   ├── __init__.py
│   │   │   ├── document_mapper.py
│   │   │   └── sql_mapper.py
│   │   ├── repositories
│   │   │   ├── __init__.py
│   │   │   ├── abcs.py
│   │   │   ├── inmemory_repo.py
│   │   │   ├── nosql_repo.py
│   │   │   └── sql_repo.py
│   │   ├── task_queue.py
│   │   └── unit_of_work
│   │       ├── __init__.py
│   │       └── abcs.py
│   ├── domain
│   │   ├── __init__.py
│   │   ├── events
│   │   │   ├── __init__.py
│   │   │   └── abcs.py
│   │   ├── messages
│   │   │   ├── __init__.py
│   │   │   ├── commands
│   │   │   │   └── __init__.py
│   │   │   └── queries
│   │   │       └── __init__.py
│   │   └── models
│   │       ├── __init__.py
│   │       ├── abcs.py
│   │       ├── aggregates
│   │       │   ├── __init__.py
│   │       │   └── abcs.py
│   │       ├── entities
│   │       │   └── __init__.py
│   │       ├── services.py
│   │       └── value_objects
│   │           └── __init__.py
│   ├── entrypoints
│   │   ├── __init__.py
│   │   ├── fastapi_routers
│   │   │   ├── __init__.py
│   │   │   └── items
│   │   │       ├── __init__.py
│   │   │       └── schemas.py
│   │   └── flask_blueprints
│   │       ├── __init__.py
│   │       └── rooms
│   │           ├── __init__.py
│   │           └── schemas.py
│   ├── persistence
│   │   ├── __init__.py
│   │   ├── document_collections.py
│   │   └── sql_tables.py
│   ├── tests
│   │   ├── e2e
│   │   │   └── __init__.py
│   │   ├── features
│   │   │   ├── feature.feature
│   │   │   └── step_defs
│   │   │       └── __init__.py
│   │   ├── integration
│   │   │   ├── __init__.py
│   │   │   ├── adapters
│   │   │   │   └── test_email.py
│   │   │   └── persistence
│   │   └── unit
│   │       ├── __init__.py
│   │       ├── domain
│   │       └── usecases
│   └── usecases
│       ├── README.md
│       ├── __init__.py
│       ├── abcs.py
│       ├── command_usecases
│       │   └── __init__.py
│       └── query_usecases
│           └── __init__.py
├── entrypoint.sh
├── flask_app.py
├── flask_cli
│   ├── __init__.py
│   └── commands
│       └── __init__.py
├── gunicorn.py
├── message_bus.py
└── sqlalchemy_app.py

```

</details>

**Comment by hjwp** [comment]
awesome!  we'd be very, very interested to hear how you get on.  keep us posted?  and/or blog about it?

we're happy to keep answering questions.

i've not personally had to deal with multiple bounded contexts within the same app, your approach looks pretty close to what I would imagine tho.  maybe you'll find the "entrypoints" are the ones that occasionally don't fit into a single context?  let us know about that too :)

**Comment by okeyokoro** [comment]
> awesome! we'd be very, very interested to hear how you get on. keep us posted? and/or blog about it?

awesome! will do! 😄

> we're happy to keep answering questions.

thanks so much!

> i've not personally had to deal with multiple bounded contexts within the same app
^ yeah, i'm applying the techniques to a monolith (always easier/faster to start out since i'm usually working as a solo developer...and this architecture would make it trivial to evolve into microservices later on)

> maybe you'll find the "entrypoints" are the ones that occasionally don't fit into a single context?
interesting, i'll keep an eye out for that

> let us know about that too :)
👍😁

**Comment by stickperson** [comment]
Any updates on this?
