### ISSUE TITLE
Question: How this works withoug receiving IndexError: pop from empty list

### ISSUE THREAD

**Issue by ppmadalin** [cosmicpython/code#16]
Hi Harry & Bob,

I was not able to make this piece of code work without adding a checking for an empty list:

```python
 def collect_new_events(self):
        for product in self.products.seen:
            while product.events:
                yield product.events.pop(0)
```
With this, I am getting the following exception: `IndexError: pop from empty list`

Is this working without checking if `product.events` is empty?

Reference: 
https://github.com/cosmicpython/code/blob/e3de63c922c2094d63949949b4cdf776fb5462dc/src/allocation/service_layer/unit_of_work.py#L28

**Comment by hjwp** [comment]
well we're glad to hear that someone is trying to run the code!   i guess you figured out the bug?  

how are you enjoying the book in general?

**Comment by hjwp** [comment]
well that `product.events.pop` is inside a `while product.events` block so in theory it can never be empty, and you should never be able to cause an `IndexError`

have you got a repo somewhere you can share, maybe with a test case that reproduces the error?

**Comment by hjwp** [comment]
i'm glad you've been trying the exercises too! how did you find them?

**Comment by ppmadalin** [comment]
Yes, you are right. I just double-checked my code, and I found the mistake.   

They are great, and if you want to understand them, then definitely, you need to run them. Just reading and glancing through this repo is not enough. I am glad that I did this because now I have connected all the dots, and for sure when I will recommend this book, I will strongly suggest following the code examples along with the book chapters.  

Thank you, guys for writing this book, and we are waiting for more to come.
