### ISSUE TITLE
allocate_endpoint returns "OK", 202 even though there is not enough quantity in any batch

### ISSUE THREAD

**Issue by shomy4** [cosmicpython/code#37]
Hi, 

I noticed that your allocate_endpoint returns status **OK** event though there is not enough quantity in any batches.
OutOfStock event is called, thats ok, but shouldn't the client also receive the information that allocation has failed due to not having enough sku. Or have i missed something?

Anyway, your book is really great, it was a pleasure reading it!

**Comment by hjwp** [comment]
hi!  i think it depends on what the semantics of that endpoint are.  if we want to follow strict cqrs, commands are not supposed to return _any_ information other than "succeeded" or "failed".

so for a 400 error with an invalid request (maybe like a nonexistent sku) that's very likely to mean just "failed"

but for an out of stock situation, it really depends on the business process.  do we still maybe register the allocation, record the request successfully, and hope to allocate stock later?  maybe!  

i think more likely, as you say, we should send back some sort of "failed" message.  but then are we saying the client should retry?   it's not a decision you can make in isolation.
