### ISSUE TITLE
Postgre/API never came up

### ISSUE THREAD

**Issue by uguryiilmz** [cosmicpython/code#62]
In chapter 4 for the service layer, when i run the end to end tests i keep getting this error. When i try to comment out postgresql and use sqllite intead, the error turn insto api never came up. Are end to end tests supposed to use real database? I thought they would use sqllite like integration tests. These are the errors i'm getting.
<img width="816" alt="Screen Shot 2023-03-21 at 11 40 29 PM" src="https://user-images.githubusercontent.com/20513149/226796235-7379a98c-b56d-4da6-8bf1-ba7821c038a2.png">
<img width="704" alt="Screen Shot 2023-03-21 at 11 41 26 PM" src="https://user-images.githubusercontent.com/20513149/226796368-c8140d78-bace-45b3-932b-efecc5592b2a.png">

when i try to dive deeper, i noticed the error is coming from web server

<img width="806" alt="Screen Shot 2023-03-21 at 11 42 32 PM" src="https://user-images.githubusercontent.com/20513149/226796502-0cd6161f-a06c-43a0-a4ca-3d744d1f97bc.png">

any idea why this might be happening? Thanks for the great book, it helped me a lot!

**Comment by uguryiilmz** [comment]
I was able to run the end-to-end tests with the following approach:

my first misunderstanding was that end to end tests need a service up to run. it expects you to run the flask server on port 5001. however, docker is not really working -i noticed there were some issues related to that here. so i needed to run my flask server locally on a separate terminal on port 5001, then when i run the tests they all passed successfully.

**Comment by hjwp** [comment]
if you're copying the code in the repo, there's a  dockerfile and a docker-compose config for runing the api + flask?
