### ISSUE TITLE
Psycopg2 error: Symbol not found _PQbackendPID

### ISSUE THREAD

**Issue by uguryilmazunified** [cosmicpython/code#64]
I noticed this error is happening on m1 chip macbook due to pscopg-binary. 

After i switched to python 3.9+, the error has gone away. Also this error doesn't happen when you run the tests via docker, since i believe it's already using 3.9 however when i tried to run the tests in my local with pytest, i saw this error.

**Comment by hjwp** [comment]
hope it's ok if i close this?  i don't have a mac and i'm not sure i have any time to fix it...
