### ISSUE TITLE
Should the allocation directory has __init__.py

### ISSUE THREAD

**Issue by haibin** [cosmicpython/code#7]
I'm not sure if the question is related to the book. But I keep wondering why the `allocation` directory does not have a `__init__.py`.

**Comment by hjwp** [comment]
I have to admit that I don't really understand the details, but essentially __init__.py became optional in python 3 dot something. https://www.python.org/dev/peps/pep-0420/

**Comment by hjwp** [comment]
maybe this is a better explanation https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3-3

**Comment by hjwp** [comment]
I added some dunderinits.  by the principle of least surprise, it's the sensible thing to do.  Thanks for the prompt!
