### ISSUE TITLE
Too much code in domain/service that could be in database (too much python that could be SQL)

### ISSUE THREAD

**Issue by drforse** [cosmicpython/code#92]
While reading I was thinking on one question. Before this book my code never had a service layer, business logic either in fastapi endpoints, or in separate modules created for certain features. So yeah, I didn't really have so strict rules, as the book suggests. And the thing is... My repositories and domain (not really, but also not orm) models were pretty different from what is in the book. First, there were always a model for each database table, no value-entity-agregator, just a reflection of the database, and the repositories - one repository per db table. And the repositories looked like that:
```
﻿﻿class UserRepository(BaseRepository):
    def get_by_id(self, id_: int) -> User:
        # work with SA model
        # put the results in domain model User and return
﻿﻿
    # more methods
﻿﻿
    # some difficult code, dependent on several tables
    def get_all_users_filtered_by_money_spent(self, min_money_spent, max_money_spent) -> list[Users]:
        # work with users and transactions models
```
﻿﻿
﻿The thing is that usually I put as much as I could in the repo to not aggregate anything in Python code, but aggregate most of it in SQL, maybe as complex as using CTE with five different tables joined sometimes, although usually not as complex, but definitely not as simple as in the book where you get everything in the code to one aggregator and work on it in service layer. So now I have a really big challenge, and I am not even really sure if that's so good to make work in service layer while you could just write a complex but fast SQL query...

Also, nothing auto-generated by database like autoincrementing ids can be used in service... :/

**Comment by hjwp** [comment]
it sounds like you're exploring the tradeoffs between putting more logic into SQL vs keeping it in the domain/python...  i'm sorry i don't have a simple answer or suggestion for you here!  Just to say, yes, this is a tradeoff, and there's no right or wrong answer in general.

you _can_ use database-generated things if you really want to, i think most people tend to avoid it because they feel it's an implementation-level concern that shouldn't leak into the domain.

**Comment by hjwp** [comment]
I'm closing this as an issue but very happy to continue the discussion here!

**Comment by drforse** [comment]
> it sounds like you're exploring the tradeoffs between putting more logic into SQL vs keeping it in the domain/python...  i'm sorry i don't have a simple answer or suggestion for you here!  Just to say, yes, this is a tradeoff, and there's no right or wrong answer in general.
> 
> you _can_ use database-generated things if you really want to, i think most people tend to avoid it because they feel it's an implementation-level concern that shouldn't leak into the domain.


Okay, I understand. It's interesting how the book would change with the approach of putting more logic in SQL instead of domain. Maybe you have some similar understandable books or articles but with the mentioned approach in mind?

**Comment by drforse** [comment]
It would be cool to see what you and other people think about it, not an ANSWER, but thoughts. Why do some prefer one over the other, and what are the pros and cons of both approaches.
Now I realize that it's not just a small question, but a big topic for discussion

**Comment by drforse** [comment]
I always liked to put a lot of logic in SQL because in my experience in my projects it's generally much faster, so the main reason is optimization.
But it's not like I checked each case whether it's faster in python or SQL, it's just that I was getting the need to move logic to SQL so often that eventually I started putting as much as I could in SQL without thinking if it's really needed here.
